CREATE TABLE Filial
(
    IdFilial BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NomeLoja VARCHAR(150) NOT NULL,
    CNPJ INTEGER NOT NULL,
    Logradouro VARCHAR(100) NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    Complemento VARCHAR(50) NOT NULL,
    Bairro VARCHAR(50) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE,
    DateCreated TIMESTAMP NOT NULL,
    PRIMARY KEY (IdFilial)
);

CREATE TABLE Perfil
(
    IdPerfil INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NomePerfil VARCHAR(50) NOT NULL,
    PRIMARY KEY (IdPerfil)
);

CREATE TABLE Usuario
(
    IdUser BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Nome VARCHAR(50) NOT NULL,
    IdPerfil INTEGER NOT NULL,
    Login VARCHAR(10) NOT NULL,
    Senha VARCHAR(8) NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE,
    DateCreated TIMESTAMP NOT NULL,
    PRIMARY KEY (IdUser),
    FOREIGN KEY (IdPerfil) REFERENCES Perfil(IdPerfil)
);

CREATE TABLE Cliente
(
    IdCliente BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CPF INTEGER NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    Sexo VARCHAR(9),
    DataNascimento DATE,
    IsActive BOOLEAN DEFAULT TRUE,
    DateCreated TIMESTAMP NOT NULL,
    PRIMARY KEY (IdCliente)
);

/*************************************************************************/

CREATE TABLE Colecao
(
    IdColecao INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Nome VARCHAR(50) NOT NULL,
    Periodo VARCHAR(9) NOT NULL,
    Ano INTEGER NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE,
    DateCreated TIMESTAMP NOT NULL,
    PRIMARY KEY (IdColecao)
);

CREATE TABLE Produto
(
    IdProduto BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    Codigo INTEGER NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    Descricao VARCHAR(150) NOT NULL,
    IdColecao INTEGER NOT NULL,
    Tipo VARCHAR(20) NOT NULL,
    Cor VARCHAR(20) NOT NULL,
    ValProducao DECIMAL(14,2) NOT NULL,
    ValVenda DECIMAL(14,2) NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE,
    DateCreated TIMESTAMP NOT NULL,
    PRIMARY KEY (IdProduto),
    FOREIGN KEY (IdColecao) REFERENCES Colecao(IdColecao)
);

CREATE TABLE Estoque
(
    IdEstoque BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IdProduto BIGINT NOT NULL,
    IdFilial BIGINT NOT NULL,
    Tamanho VARCHAR(2) NOT NULL,
    Quantidade INTEGER NOT NULL,
    DateCreated TIMESTAMP NOT NULL,
    PRIMARY KEY (IdEstoque),
    FOREIGN KEY (IdProduto) REFERENCES Produto(IdProduto),
    FOREIGN KEY (IdFilial) REFERENCES Filial(IdFilial)
);

/**********************************************************************************************/

CREATE TABLE Venda
(
    IdVenda BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IdCliente BIGINT NOT NULL,
    IdFilial BIGINT NOT NULL,
    IdUser BIGINT NOT NULL,
    TotalVenda DECIMAL(14,2) NOT NULL,
    DateCreated TIMESTAMP NOT NULL,
    PRIMARY KEY (IdVenda),
    FOREIGN KEY (IdCliente) REFERENCES Cliente(IdCliente),
    FOREIGN KEY (IdFilial) REFERENCES Filial(IdFilial),
    FOREIGN KEY (IdUser) REFERENCES Usuario(IdUser)
);

CREATE TABLE ItemVenda
(
    IdItemVenda BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IdVenda BIGINT NOT NULL,
    IdProduto BIGINT NOT NULL,
    Tamanho VARCHAR(2) NOT NULL,
    Quantidade INTEGER NOT NULL,
    ValorTotal DECIMAL(14,2) NOT NULL,
    DateCreated TIMESTAMP NOT NULL,
    PRIMARY KEY (IdItemVenda),
    FOREIGN KEY (IdVenda) REFERENCES Venda(IdVenda),
    FOREIGN KEY (IdProduto) REFERENCES Produto(IdProduto)
);